# Generated by Django 4.0.4 on 2022-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerup', '0002_alter_client_address_alter_client_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last Name', max_length=250),
        ),
    ]
